[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "light"
primaryColor = "#1e90ff"         # Dodger blue (buttons/sliders)
backgroundColor = "#f5f5f5"      # Light gray background
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "sans serif"

[layout]
wide = true

[client]
showSidebarNavigation = false
